FROM node:lts-alpine3.18

RUN npm i -g @nestjs/cli

RUN npm install --save pg typeorm @nestjs/typeorm @nestjs/config

RUN npm install --save adminjs
RUN npm install --save @adminjs/nestjs
RUN npm install --save @adminjs/typeorm

RUN npm install --save @nestjs/websockets
